# Generated by Django 4.0.1 on 2022-05-01 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Votlins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidates', models.TextField()),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
