# Generated by Django 4.0.1 on 2022-05-13 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votinglist', '0002_votlins_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='votlins',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
